ArneBinder/pytorch-ie-hydra-template-1

- src/utils/__init__.py
This is relevant information that was not logged before.
> log the dataset config for training

- README.md
> fix structure (docs): add prediction related files

- evaluate.py
- predict.py
- train.py
> register omegaconf "replace" resolver for evaluate und predict pipelines

- src/training_pipeline.py
> don't convert to absolute paths

- .pre-commit-config.yaml
- requirements.txt
- src/train.py
Primarily, this integrates https://github.com/ChristophAlt/pytorch-ie/pull/245.
> update pytorch-ie to latest master

- src/evaluate.py
- src/predict.py
- src/train.py
> convert Path to str for hydra.main()

- configs/logger/aim.yaml
- configs/logger/mlflow.yaml
Put everything into one place: `logs/logger/<logger_name>`
> improve local logger data location

- src/datamodules/datamodule.py
This fixes #69. In fact, multi device training was broken until this PR.
> PieDataModule: use setup(stage) instead of prepare_data()

- setup_symlinks.sh
this avoids potential problems, e.g. on the cluster
> use absolute path as target for symlinks

- tests/test_sweeps.py
... by using tiny-bert and fewer epochs, trials, etc.
> speedup sweep tests

- README.md
> fix "How to Run" section at the end of the readme

- .pre-commit-config.yaml
- configs/hydra/default.yaml
- src/evaluate.py
- src/hydra_callbacks/__init__.py
- src/hydra_callbacks/save_job_return_value.py
- src/predict.py
- src/train.py
> Save job results

- README.md
add detailed information for model training, evaluation, inference, and document evaluation to the project readme template
> improve the project readme template

- requirements.txt
Especially, this integrates https://github.com/ArneBinder/pie-utils/pull/50.
> use fixed pie-utils v0.5.1

- requirements.txt
... and add some documentation to pie-utils dependency
> upgrade pytorch-ie to 0.19.0

- src/hydra_callbacks/save_job_return_value.py
If we don't do this, `DataFrame.describe()`, which we use to aggregate, does not work as expected.
> Fix aggregate result: remove non-numeric columns

- configs/dataset/_add_candidate_relations.yaml
- configs/dataset/_add_partitions.yaml
- configs/dataset/_add_reversed_relations.yaml
- requirements.txt
This integrates https://github.com/ChristophAlt/pytorch-ie/pull/337, see there for further information.
Note: CI is just read because the Huggingface dataset `conll2003` is currently not reachable.
> don't infer `result_document_type` in `(Iterable)Dataset.map()`

- README.md
- configs/dataset/from_serialized_documents.yaml
- configs/serializer/json.yaml
- requirements.txt
- src/evaluate_prediction.py
- src/serializer/json.py
- tests/unit/serializer/test_json.py
> serialize `document_type` when saving predictions

- configs/dataset/conll2003.yaml
- configs/dataset/conll2003_base.yaml
... to not be impacted by changes of scripts at https://huggingface.co/pie
> set revision for PIE dataset loading script

- configs/dataset/_add_candidate_relations.yaml
- configs/dataset/_add_partitions.yaml
- configs/dataset/_add_reversed_relations.yaml
- configs/dataset/_convert_documents.yaml
- configs/dataset/_create_test_split.yaml
- configs/dataset/_create_test_split_by_ids.yaml
- configs/dataset/_create_validation_split.yaml
- configs/dataset/_rename_splits.yaml
- configs/dataset/_select_n.yaml
- configs/dataset/conll2003.yaml
- configs/dataset/conll2003_base.yaml
- configs/dataset/from_serialized_documents.yaml
- requirements.txt
- src/document/types.py
- src/evaluate.py
- src/evaluate_documents.py
- src/predict.py
- src/serializer/json.py
- src/train.py
- tests/unit/serializer/test_json.py
see https://github.com/ChristophAlt/pytorch-ie/releases/tag/v0.28.0 and https://github.com/ArneBinder/pie-datasets/releases/tag/v0.3.1
> upgrade `pytorch-ie` to 0.28.0

- configs/metric/span_lengths_characters.yaml
- configs/metric/span_lengths_characters_per_label.yaml
- configs/metric/span_lengths_tokens.yaml
- src/document/types.py
`span_lengths_characters`, `span_lengths_characters_per_label`, and `span_lengths_tokens`
> add more metric configs

- src/metrics/__init__.py
- tests/dataset_builders/__init__.py
- tests/dataset_builders/pie/test_conll2003.py
- tests/unit/metrics/test_f1.py
- tests/unit/taskmodules/test_transformer_token_classification.py
> add tests for example code (dataset, taskmodule, metric)

- dataset_builders/pie/conll2003/requirements.txt
- requirements.txt
context: https://github.com/ArneBinder/pie-datasets/issues/93
> update dependency: pie-datasets>=0.8.1,<0.9.0

- configs/metric/relation_argument_character_distances.yaml
- configs/metric/relation_argument_token_distances.yaml
- requirements.txt
This requires pie-modules [0.10.8](https://github.com/ArneBinder/pie-modules/releases/tag/v0.10.8) because of https://github.com/ArneBinder/pie-modules/pull/68.
> add span coverage metric configs

- configs/dataset/drugprot_base.yaml
- configs/dataset/drugprot_prepared.yaml
- configs/experiment/drugprot.yaml
- configs/model/sequence_classification_with_pooler.yaml
- configs/taskmodule/re_text_classification_with_indices.yaml
add dataset, model, taskmodule and experiment config for drugprot
> new example: RE on drugprot

- src/hydra_callbacks/save_job_return_value.py
This fixes a regression introduced in #178.
> fix `SaveJobReturnValueCallback` for single run

- src/hydra_callbacks/save_job_return_value.py
From the docstring:
`sort_markdown_columns`: bool (default: False) If True, the columns of the markdown table are sorted alphabetically.
> add parameter `sort_markdown_columns` to `SaveJobReturnValueCallback`

- tests/conftest.py
this model: https://huggingface.co/prajjwal1/bert-tiny
> use `bert-tiny` in all train tests

- requirements.txt
- src/serializer/json.py
- tests/test_train.py
to simplify the serializer and **allow appending**
This requires pie-datasets [0.10.4](https://github.com/ArneBinder/pie-datasets/releases/tag/v0.10.4) because of https://github.com/ArneBinder/pie-datasets/pull/136.
> `JsonSerializer`: use (Iterable)Dataset.(to_json|from_json)

- requirements.txt
- src/evaluate.py
- src/evaluate_documents.py
- src/train.py
... but `dataset.to_document_type(..., downcast=False)` instead.
In preparation for https://github.com/ArneBinder/pie-core/issues/69.
> don't use `WithDocumentTypeMixin.convert_dataset`
