.github/workflows/tests.yml
configs/predict.yaml
configs/serializer/json.yaml
predict.py
src/prediction_pipeline.py
src/serializer/__init__.py
src/serializer/json.py
tests/shell/test_basic_commands.py
tests/unit/serializer/test_json.py

This implements a very simply prediction pipeline in analogy to the test and train pipelines. It can be called like:
```
python predict.py
```
where this happens behind the scene:
```
python predict.py \
dataset=conll2003 \
dataset_split=test \
model_name_or_path=pie/example-ner-spanclf-conll03 \
pipeline.predict_field=entities \
out_path=prediction/conll2003_test.jsonl
```
To execute on the gpu and set a batch size, add these parameters:
```
+pipeline.device=0 +pipeline.batch_size=64
``` 
This requires: #26 
EDIT: This also fixes the GitHub tests action (previously, unit tests were not executed).

implement prediction pipeline with json serializer

---

configs/experiment/conll2003.yaml
configs/logger/wandb.yaml
train.py

Some tweaks to improve the default setup. Notably, the wandb project name will be created from the `$name`. Previously, it was just used to define the name of the run (i.e. to set `wandb.name`).

Improve wandb logging

---

predict.py
test.py
train.py

otherwise it is not easily possible to use modules from `src` within configs

add src to pythonpath in train / test / predict scripts

---

configs/logger/aim.yaml

add missing entry `test_metric_prefix: test/`

fix aim logger config

---

configs/dataset/_create_validation_split.yaml
configs/dataset/_select_n.yaml
configs/dataset/conll2003_base.yaml
configs/dataset/conll2003_select_n.yaml
src/utils/__init__.py
src/utils/dataset.py

implements the following functions in the `utils` package:
- `process_dataset`
- `convert_documents`
- `add_test_split`
- `rename_splits`
- `select`
and example dataset configs that contain respective documentation:
- `_create_validation_split`
- `_select_n`
- `conll2003_base`
- `conll2003_select_n`

dataset utils

---

.env.example
README.md

* add `TOKENIZERS_PARALLELISM=false` to the example env file `.env.example`
* add optional instruction to the quickstart section in the readme for setting up `.env` file

Improve example env file and add quickstart instruction

---

configs/datamodule/default.yaml
src/datamodules/__init__.py
src/datamodules/datamodule.py
src/evaluate.py
src/train.py

The data is encoded twice: when calling datamodule.setup() and in the datamodule hook when starting the training (similar for evaluation). This fixes that by creating a datamodule with just prepare_data() which does the encoding. taskmodule.prepare() is called directly from the train script.

Fix double encode

---

README.md
src/train.py

... and raise an exception when the model class is unknown. Also add examples for how to set `additional_model_kwargs` for the remaining PIE models.
NOTE: We set `additional_model_kwargs` just for the model that is used for testing and throw an exception in the other cases because the user should be aware of this and do it by its own. Otherwise the train script would be cluttered with code that the user does not need at all. 
This fixes #67.

set additional_model_kwargs explicitly per model class

---

src/utils/utils.py

Log `monitor_metric`, `monitor_mode`, and `model_save_dir` in `log_hyperparameters()`. Especially, `model_save_dir` is quite important (to know where to find the trained model).

log more parameters

---

configs/logger/aim.yaml
configs/logger/csv.yaml
configs/logger/mlflow.yaml
configs/logger/wandb.yaml

This PR modifies the logger configs in the following way:
- for csv : align the `save_dir` with the respective values of the aim and mlflow loggers, i.e. `${paths.log_dir}/logger/csv/`
- for csv, aim, mlflow, and wandb: append the value of pipeline_type, i.e. `training`, `evaluation`, or `prediction`, to the experiment / project name
- for csv, and mlflow:  align the (experiment_)name with the respective value of aim, i.e. `${replace:${name},/,-}-${pipeline_type}`

Improve logger paths

---

src/train.py

Before this PR, not the best model (according to the checkpoint callback) was saved when training finishes, but just the last checkpoint. This PR fixes this by correctly loading the best checkpoint into the model before saving it.
This PR also modifies the condition when a model is saved to **not** require `train=true`. This allows to save zero-shot variants of models e.g. to evaluate them with the same scripts as trained few-shot models etc. Model saving can still easily disabled by setting `model_save_dir=null`.

Fix saving the best model after training

---

tests/test_eval.py

`test_train_eval()` occasionally fails because the test F1 remains zero. Now, we ensure reproducibility by setting the `seed` and `trainer.deterministic=True`. Furthermore, we just check that the test scores are the same as after training (and do not ensure that it is above zero).

make test_train_eval() deterministic

---

src/utils/utils.py

Integrate changes from https://github.com/ashleve/lightning-hydra-template/pull/479:
"This change make the `hparams` sent to all loggers. Before: The `hparams` will be only sent to the first logger if `many_loggers.yaml` is used, so the other logger only get a default empty Dict."

fix hparams logging when using multiple loggers

---

configs/predict.yaml
configs/serializer/json.yaml

This eases the creation of future serializers because we do not set the path in the default predict config anymore.

set the serializer path in the json serializer config

---

src/evaluate.py
src/predict.py
src/train.py

With this PR, everything from models and taskmodules is imported in the main entry scripts (train.py, evaluate.py, and predict.py) to register any user defined classes to make them work with Auto* classes.
This should fix #73.

load all models and taskmodules in main entry scripts

---

configs/dataset/from_serialized_documents.yaml
configs/evaluate_documents.yaml
configs/predict.yaml
configs/serializer/json.yaml
tests/test_predict.py

This PR implements the following changes:
- use the `dataset_split` parameter in the `serializer.path` instead of in the `prediction_save_dir`
- do not predefine the `data_files` parameter in the `from_serialized_documents` dataset config (to also allow using `data_dir`)

align input and output paths

---

tests/test_predict.py

this is a `slow` test, so this was not noticed before

fix `test_train_predict()`

---

configs/taskmodule/transformer_token_classification.yaml
requirements.txt
src/taskmodules/__init__.py
src/taskmodules/transformer_token_classification.py
tests/unit/taskmodules/test_transformer_token_classification.py

with version from https://github.com/ArneBinder/pie-modules/pull/6

update transformer token classification taskmodule

---

requirements.txt
src/evaluate.py
src/train.py
src/utils/logging_utils.py

This PR improves the hyperparameter logging when executing `train.py` or `evaluate.py` in the following ways, i.e. `log_hyperparameters()`:
- the hydra-run config gets resolved before logging it, that means `ConfigDict` entries are correctly un-nested (compare the `dataset` entry in the W&B run config view, for instance)
- remove duplicated entries by not logging `model._config()` and `taskmodule._config()` at all, because the model parameters are automatically logged by calling `self.save_hyperparameters()` in the model and in the future each model should receive `taskmodule_config` as parameter, so that will get logged as well (`taskmodule._config()` is currently still logged in some cases for backwards compatibility)
- the method allows for arbitrary keyword arguments that will get …

improve hyperparameter logging

---

requirements.txt
src/serializer/__init__.py
src/serializer/brat.py
tests/unit/serializer/test_brat.py

This adds Brat Serializer which writes model predictions to annotation files (.ann) in Brat format. It requires a `layers` parameter to specify the annotation layers to serialize. For now, it supports layers containing _LabeledSpan_, _LabeledMultiSpan_, and _BinaryRelation_ annotations. If a `gold_label_prefix` is provided, the gold annotations are serialized with the given prefix.  Otherwise, only the predicted annotations are serialized. A `document_processor` can be provided to process documents before serialization.
```python
from src.serializer import BratSerializer
from pie_modules.annotations import BinaryRelation, LabeledSpan
from pie_modules.documents import TextDocumentWithLabeledSpansAndBinaryRelations
document = TextDocumentWithLabeledSpansAndBinaryRelations(
text="Harry lives …
```

add brat serializer

---

requirements.txt

fix: add dependency for relation argument distance metric configs

---

configs/metric/span_coverage_characters.yaml
configs/metric/span_coverage_tokens.yaml

This requires pie-modules [0.10.8](https://github.com/ArneBinder/pie-modules/releases/tag/v0.10.8) because of https://github.com/ArneBinder/pie-modules/pull/68.

add span coverage metric configs again

---

configs/pipeline/ner_re_pipeline.yaml
src/pipeline/ner_re_pipeline.py
tests/unit/pipeline/test_ner_re_pipeline.py

This PR parameterise the layer names for the NER-RE pipeline and tests.

Update NER-RE pipeline

---

src/evaluate.py
src/predict.py

from `pie_modules` in `evaluate.py` and `predict.py`. Otherwise, models trained with classes from `pie_modules.models` or `pie_modules.taskmodules` would break these scripts

fix missing model and taskmodule imports

---

src/serializer/brat.py
tests/unit/serializer/test_brat.py

... that maps the *names* of layers to serialize to *what* to serialize. The latter needs to be one of these string values: `"gold"`, `"prediction"`, or `"both"`.

brat serializer: make `layers` parameter a dict

---

src/serializer/brat.py
tests/unit/serializer/test_brat.py

This PR adds the parameters `metadata_gold_id_keys` and `metadata_prediction_id_keys` to the `BratSerializer`:
- `metadata_gold_id_keys`: A dictionary mapping layer names to metadata keys that contain the gold annotation IDs.
- `metadata_prediction_id_keys`: A dictionary mapping layer names to metadata keys that contain the prediction annotation IDs.
Usage example:
```bash
+metadata_gold_id_keys.labeled_spans=entity_ids 
```
This will use the entries in `entity_ids` from the document metadata as IDs for when serializing the gold annotations from the `labeled_spans` layer.

brat serializer: allow using annotation ids from document metadata

---

configs/extras/default.yaml

As described in the issue #175, the default tags settings in the config file `extras/default.yaml` expect tags to be set. If no tags are set, the user is expected to enter appropriate tags. However, this lead to confusion as the process stops and awaits the user input.
</b>
For this reason, the `enforce_tags` variable is set to `False` instead of `True` in the config file.

fixes #175 default tags setting 

---

.pre-commit-config.yaml
README.md
setup.cfg
src/datamodules/datamodule.py
src/metrics/f1.py
src/pipeline/ner_re_pipeline.py
src/serializer/brat.py
src/serializer/interface.py
src/taskmodules/transformer_token_classification.py
src/utils/rich_utils.py

to fix the following error on CI:
```
An error has occurred: InvalidManifestError: 
==> File /home/runner/.cache/pre-commit/repogtzzmo34/.pre-commit-hooks.yaml
==> At Hook(id='docformatter-venv')
==> At key: language
=====> Expected one of conda, coursier, dart, docker, docker_image, dotnet, fail, golang, haskell, lua, node, perl, pygrep, python, r, ruby, rust, script, swift, system but got: 'python_venv'
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: The process '/opt/hostedtoolcache/Python/3.9.21/x64/bin/pre-commit' failed with exit code 1
```
Notes:
- via `pre-commit autoupdate`, but switched back to specific revision for docformatter
- this also adds `exclude: "^data/.*"` to the `.pre-commit-config.yaml`: exclude content of root `data` folder

update `pre-commit` hooks

---

configs/hydra/default.yaml
src/hydra_callbacks/save_job_return_value.py

This PR combines the changes of three PRs in a downstream project.
1. add parameter `multirun_aggregator_blacklist` to `SaveJobReturnValueCallback` 
...and also set `multirun_aggregator_blacklist: ["min", "25%", "50%", "75%", "max"]` as default value in the config. From the docstring:
```
multirun_aggregator_blacklist: List[str] (default: None)
A list of keys to exclude from the aggregation (of multirun results), such as "count" or "25%". If None,
all keys are included. See pd.DataFrame.describe() for possible aggregation keys.
For numeric values, it is recommended to use ["min", "25%", "50%", "75%", "max"]
which will result in keeping only the count, mean and std values.
```
2. fix multirun result as markdown for `integrate_multirun_result=False`
3. set `integrate_multirun_result` per …

Improve `SaveJobReturnValueCallback`

---

src/predict.py

This fixes this error (in fact, inference with model weights from checkpoint was broken until now):
```
TypeError: The classmethod `SimpleGenerativeModel.load_from_checkpoint` cannot be called on an instance. Please call it on the class type and make sure the return value is used.
```

call `load_from_checkpoint` on model type instead of model instance

---

configs/metric/f1.yaml

because this allows to infer labels. This enables inference of labels per default.

use F1 metric from `pytorch_ie`

---

src/hydra_callbacks/save_job_return_value.py

This PR fixes the aggregation logic and adds the following parameters to the `SaveJobReturnValueCallback`:
```
multirun_create_ids_from_overrides: bool (default: True)
Create job identifiers from the overrides of the jobs in a multi-run. If False, the job index is used as
identifier.
markdown_round_digits: int (default: 3)
The number of digits to round the values in the markdown file. If None, no rounding is applied.
multirun_job_id_key: str (default: "job_id")
The key to use for the job identifiers in the integrated multi-run result.
```
Error case that was fixed:
```
python src/evaluate_documents.py \
dataset=cdcp_base,abstrct_base \
metric=count_text_characters \
--multirun
```
would cause:
```
[2025-01-30 18:07:43,869][src.hydra_callbacks.save_job_return_value.SaveJobReturnValueCallbac …
```

Improve `SaveJobReturnValueCallback` again

---

configs/paths/default.yaml

remove trailing slash in default `data_dir` and `log_dir`

remove dublicated slash in default paths 

---

src/hydra_callbacks/save_job_return_value.py

This adds the following parameters to `SaveJobReturnValueCallback` (from the docstring):
```
paths_file: str (default: None)
The file to save the paths of the log directories to. If None, the paths are not saved.
path_id: str (default: None)
A prefix to add to each line in the paths_file separated by a colon. If None, no prefix is added.
multirun_paths_file: str (default: None)
The file to save the paths of the multi-run log directories to. If None, the paths are not saved.
multirun_path_id: str (default: None)
A prefix to add to each line in the multirun_paths_file separated by a colon. If None, no prefix is added.
```

Improve `SaveJobReturnValueCallback` v3

---

src/analysis/combine_job_returns.py
src/analysis/common.py

from the help (`python src/analysis/combine_job_returns.py -h`):
```
usage: combine_job_returns.py [-h] [--paths-file PATHS_FILE] [--use-aggregated] [--file-name FILE_NAME] [--columns COLUMNS [COLUMNS ...]] [--unpack-multirun-results]
[--unpack-multirun-results-with-job-id] [--transpose] [--round-precision ROUND_PRECISION] [--in-percent] [--reset-index]
[--format {markdown,markdown_mean_and_std,json}]
Combine job returns and show as Markdown table or Json
optional arguments:
-h, --help            show this help message and exit
--paths-file PATHS_FILE
Path to the file containing the paths to the job returns
--use-aggregated      Whether to use the aggregated job returns
--file-name FILE_NAME
Name of the file to write the aggregated job returns to
--columns COLUMNS [COLUMNS ...]
Columns to …
```

add `combine_job_returns.py`

---

src/datamodules/datamodule.py

but create the `(Iterable)TaskEncodingDataset` "manually" from the encodings
context: https://github.com/ArneBinder/pie-core/pull/61

dont pass `as_dataset` to `taskmodule.encode`

---

configs/serializer/brat.yaml
configs/serializer/json.yaml
src/predict.py
src/serializer/interface.py

this allows to pass the `split` during (hydra) instantiation of the serializer
context: #193

`DocumentSerializer` implementations require `split` parameter

---

tests/test_predict.py

this was broken because of https://github.com/ArneBinder/pytorch-ie-hydra-template-1/pull/193 (note that the test does not run on CI because it is marked as `slow`)

fix `test_train_predict`

---

configs/pipeline/_from_pretrained.yaml

`pytorch_ie.auto` will be removed soon from PyTorchIE (see follow-ups of https://github.com/ArneBinder/pytorch-ie/pull/456)

import `AutoPipeline` from `pytorch_ie` root instead of `pytorch_ie.auto`

---

tests/unit/serializer/test_brat.py

...uncovered by using `pie-core`.
Use `InvalidAnnotation` and `InvalidDocument` for tests that check for exceptions to be independent of `Annotation` / `Document` location.

fix brat serializer tests

---

src/train.py

From `pytorch-lightning` 2.2 onwards, the models are not automatically set to train mode during training (see section "Improved Handling of Evaluation Mode" in the [release notes](https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.2.0)). this affects e.g. loaded Huggingface transformer models.
With this PR, we explicitly set the model into training mode via `model.train()` before the actual training starts.
To just partly train the model (e.g. only some layers), the user is advised to override the `train()` method in their model.

set model to training mode before starting training
